version: '3.8'

services:
  nexora-db:
    image: postgres:16-alpine
    container_name: nexora-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - nexora-db-data:/var/lib/postgresql/data

  nexora-redis:
    image: redis:7-alpine
    container_name: nexora-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - nexora-redis-data:/data
    command: redis-server --appendonly yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: nexora-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - nexora-db

volumes:
  nexora-db-data:
  nexora-redis-data:
