<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="FluentAssertions" Version="7.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.14" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nexora.Domain\Nexora.Domain.csproj" />
    <ProjectReference Include="..\..\src\Nexora.Application\Nexora.Application.csproj" />
    <ProjectReference Include="..\..\src\Nexora.Infrastructure\Nexora.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Nexora.Persistence\Nexora.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Nexora.Api\Nexora.Api.csproj" />
  </ItemGroup>

</Project>
